name: Glitch Automerge

on:
  push:
    branches: [ glitch ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_message: '🎉 Updated with Glitch',
              head: 'glitch',
              base: 'master',
            });
